# Generated by Django 6.0.8 on 2026-08-22 01:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('reports', '0001_initial'),
        ('roadmaps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='generated_by_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='weeklyreport',
            constraint=models.UniqueConstraint(condition=models.Q(('roadmap_week__isnull', False)), fields=('intern', 'roadmap_week'), name='unique_weekly_report_intern_week'),
        ),
    ]
